config/routes.rb
Rails.application.routes.draw do
	root to: 'tasks#index'
	
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'
    
  resources :tasks
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tasks
	
	before_save { self.email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 255 },
	              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
	              uniqueness: { case_sensitive: false }

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	include SessionsHelper
	
	private
	
	def require_user_logged_in
		unless logged_in?
			redirect_to login_url
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :show, :update, :destroy]

  def index
    if logged_in?
      @tasks = current_user.tasks.order(id: :desc).page(params[:page]).per(10)
    end
  end
  
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'Taskが正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Taskが投稿されませんでした'
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    
    if @task.update(task_params)
      flash[:success] = 'Taskは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Taskは更新されませんでした。'
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    
    flash[:success] = 'Taskは正常に削除されました'
    redirect_to tasks_url
  end
  
  private
  
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, except: [:new, :create]
  
#  不要の為  
#  def index
#    @users = User.order(id: :asc).page(params[:page]).per(10)
#  end

#  def show
#    @user = User.find(params[:id])
#  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = '新規ユーザ登録をしました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザ登録が出来ませんでした。'
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	
	def logged_in?
		!!current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_tasks.html.erb
<% if model.errors.any? %>
	<div id="error_explanation" class="alert alert-warning">
		<ul class="mb-0">
			<% model.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<div class="row">
	<div class="col-sm-6 offset-sm-3">
		<% flash.each do |task_type, task| %>
			<div class="alert alert-<%= task_type %>"><%= task %></div>
		<% end %>
	</div>
</div>

app/views/layouts/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
	
	<%= render 'layouts/error_tasks', model: f.object %>
	
	<div class="form-group">
		<%= f.label :content, 'タスク' %>
		<%= f.text_field :content, class: 'form-control' %>
	</div>
	
	<div class="form-group">
		<%= f.label :status, 'ステータス' %>
		<%= f.text_field :status, class: 'form-control col-sm-4' %>
	</div>
	
	<%= f.submit '送信', class: 'btn btn-outline-secondary mb-4' %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  	<div><%= link_to 'Tasklist', :root, class: 'navbar-brand' %></div>
 	 	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
  	  	<span class="navbar-toggler-icon"></span>
 	 	</button>
  	<div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
	    <div class="navbar-nav">
	    	<% if logged_in? %>
 		      <div class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></div>
				<% else %>
	      	<div class="nav-item"><%= link_to '新規ユーザ登録', new_user_path, class: 'nav-link' %></div>
	      	<div class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></div>	      
	      <% end %>
    	</div>
  	</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
    <%= render 'layouts/flash_tasks' %>
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ</h1>

<%= render 'layouts/form', task: @task %>

<%= link_to '一覧に戻る', tasks_path, class: 'btn btn-primary' %>

app/views/tasks/index.html.erb
<h1><%= current_user.name %>さんのタスク一覧</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
    	<th scope="col">id</th>
      <th scope="col">Task</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  	<% @tasks.each do |task| %>
	    <tr>
	    	<th><%= link_to task.id, task %></th>
	      <th scope="row"><%= task.content %></th>
	      <td><%= task.status %></td>
	    </tr>
	  <% end %>
  </tbody>
</table>

<%= paginate @tasks %>

<%= link_to '新規タスクの投稿', new_task_path, class: 'btn btn-primary' %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'layouts/form', task: @task %>

<%= link_to '一覧に戻る', tasks_path, class: 'btn btn-primary' %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %>のタスク詳細ページ</h1>

<p>Task:<%= @task.content %></p>
<p>Status:<%= @task.status %></p>

<%= link_to '一覧に戻る', tasks_path, class: 'btn btn-primary' %>
<%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-success' %>
<%= link_to 'このタスクを削除する', @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/users/new.html.erb
<div class="card-header text-center mb-3">
    <h1>新規ユーザ登録</h1>
</div>

<div class="row">
	<div class="col-sm-6 offset-sm-3">
		
		<%= form_with(model: @user,local: true) do |f| %>
			
			<%= render 'layouts/error_tasks', model: f.object %>
			
			<div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
			
			<%= f.submit '新規登録', class: 'btn btn-success btn-block' %>
		<% end %>
	</div>
</div>